return {
  'ConradIrwin/vim-bracketed-paste',
  'Lokaltog/vim-easymotion',
  'ggandor/leap.nvim',
  'editorconfig/editorconfig-vim',
  'godlygeek/tabular',
  'junegunn/fzf',
  'junegunn/fzf.vim',
  'justinmk/vim-dirvish',
  'majutsushi/tagbar',
  'Yggdroot/indentLine',
  'voldikss/vim-floaterm',
  'tpope/vim-abolish',
  'tpope/vim-endwise',
  'tpope/vim-fugitive',
  'tpope/vim-surround',
  'tpope/vim-repeat',
  'tpope/vim-commentary',
  'tpope/vim-unimpaired',
  'kana/vim-textobj-user',
  'dense-analysis/ale',
  'terryma/vim-multiple-cursors',
  'junegunn/goyo.vim',
  'mhinz/vim-signify',
  'rhysd/git-messenger.vim',
  'sheerun/vim-polyglot',
  'github/copilot.vim',
  {
    'folke/which-key.nvim',
    event = 'VeryLazy',
    init = function()
      vim.o.timeout = true
      vim.o.timeoutlen = 2000
    end,
    opts = {},
  },
  { 'folke/neodev.nvim', opts = {} },
  'williamboman/mason.nvim',
  -- theme
  'morhetz/gruvbox',
  'sickill/vim-monokai',
  'dracula/vim',
  'jnurmine/Zenburn',
  'haishanh/night-owl.vim',
  'ayu-theme/ayu-vim',
  'arcticicestudio/nord-vim',
  'junegunn/seoul256.vim',
  'altercation/vim-colors-solarized',
  'yuttie/hydrangea-vim',
  'NLKNguyen/papercolor-theme',
  'folke/tokyonight.nvim',
  'rebelot/kanagawa.nvim',
  { 'catppuccin/nvim', name = 'catppuccin', priority = 1000 },
  'SirVer/ultisnips',
  'neovim/nvim-lspconfig',
  'hrsh7th/nvim-cmp',
  'hrsh7th/cmp-nvim-lsp',
  'quangnguyen30192/cmp-nvim-ultisnips', -- lsp source for ultisnips
  'nvim-lua/plenary.nvim',
  -- language specific
  { 'begriffs/haskell-vim-now', ft = 'haskell' },
  { 'hashivim/vim-terraform', ft = 'terraform' },
  { 'OmniSharp/omnisharp-vim', ft = 'cs' },
  { 'Glench/Vim-Jinja2-Syntax', ft = 'jinja' },
  { 'jeetsukumaran/vim-pythonsense', ft = 'python' },
  { 'Vimjas/vim-python-pep8-indent', ft = 'python' },
  { 'simrat39/rust-tools.nvim', ft = 'rust' }, -- rust analyzer inlay
  { 'rust-lang/rust.vim', ft = 'rust' },
  { 'nvim-telescope/telescope.nvim', tag = '0.1.4' },
  { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' },
}
-- vim: ts=2 sts=2 sw=2 et
